from docx import Document
from docx.shared import Inches
import pyttsx3

def speak (text):
    pyttsx3.speak(text)


document = Document()
# adding profile picture / dimensions
document.add_picture('facecard.jpg', 
                     width = Inches(1), height = Inches(1))

#name  phone number and email details 
Name = input('what is your name')
speak('Hello ' + Name + 'How are you today?')
Phone_number = input('what is your phone number')
speak('Your contact number is ' + Phone_number)
email = input('please enter your email address')

document.add_paragraph(Name + '|' + str(Phone_number ) +'|' + '| '+ email
)

#about_me 
document.add_heading('About Me')
about_me = input('Tell me about yourself')
document.add_paragraph (about_me)

#work_experience 
document.add_heading('Work Experience')
p = document.add_paragraph()

company = input ('Enter Company')
from_date = input ('From Date')
to_date = input ('To date')

#script to run a text_file 
p.add_run (company + ' ').bold = True 
p.add_run(from_date + ' '+ to_date + '\n').italic = True


experience_details = input('Describe your experience at ' + company)
p.add_run(experience_details)

#more experiences 
while True:
    has_more_experiences = input('Do you have more experiences? Yes or No')

    if has_more_experiences ==('Yes').lower:
    
        p = document.add_paragraph()
        company = input ('Enter Company')
        from_date = input ('From Date')
        to_date = input ('To date')

        #script to run a text_file 
        p.add_run (company + ' ').bold = True 
        p.add_run(from_date + ' '+ to_date + '\n').italic = True

        experience_details = input('Describe your experience' + company)
        p.add_run(experience_details)
    else:
        break

    # -- Defining my skills 
document.add_heading ('Technical skills')
skills = input ('Please enter your technical skills')
p = document.add_paragraph(skills)
p.style ='List Bullet'


while True: 
    more_skills = input (
        'would you like to add more skills? Yes / No' )
    if more_skills == 'Yes':
        skills = input('Enter Skill')
        p = document.add_paragraph(skills)
        p.style = 'List Bullet'
    else:
        break
    # --- adding footer----

section = document.sections [0] 
footer = section.footer 
p = footer.paragraphs [0]
p.text = "cv generated by Henry's python script"

document.save('cv.docx')



